Update README with checklist for Iron Tutorial party
osrf/ros2_test_cases pull request #933
Opened 2023-04-05 08:46 UTC by Yadunund

You can see how the list is rendered here https://github.com/osrf/ros2_test_cases/tree/yadu/update_readme_for_iron

Clicking on any of the links should open the Issues tab with the appropriate label filters applied

2023-04-05 15:59 UTC, clalancette commented
Overall comments on this README from the discussion:

* Rewrite to have it be a "getting started" guide.
* Add in language saying that if you have Windows, prefer to test that.
* Add in headings for "Core" vs "Features"
* Prioritize things, putting the most important "sets" at the top

2023-04-07 15:55 UTC, Yadunund commented
Thanks for the feedback! Re-ordered the sets along with some general comments.

2023-04-07 16:17 UTC, clalancette requested changes
Other than my one comment inline, this looks pretty good to me.

@cottsay @mjcarroll @Voldivh can you please take a look as well?

2023-04-07 16:17 UTC, clalancette commented on README.md
> +  - [ ] [Installation on various plarforms](https://github.com/osrf/ros2_test_cases/issues?q=is%3Aissue+is%3Aopen+label%3Ainstallation+)
```suggestion
  - [ ] [Installation on various platforms](https://github.com/osrf/ros2_test_cases/issues?q=is%3Aissue+is%3Aopen+label%3Ainstallation+)
```

2023-04-07 16:34 UTC, clalancette approved these changes

2023-04-07 19:48 UTC, Voldivh reviewed
LGTM! As someone that have never contributed to a Tutorial Party (or seen anything related to it), the initial instructions and structure of the priority gave me enough information in order to know what to do and where to start, so I believe the discussed goals were accomplished 👍  
 
As a side note, would it be worth to add a brief section like "Why contribute?" to motivate the community to participate? Or is it explicitly enough by just stating it is a Tutorial Party?

2023-04-10 13:35 UTC, clalancette approved these changes

2023-04-10 13:36 UTC, clalancette commented
> As a side note, would it be worth to add a brief section like "Why contribute?" to motivate the community to participate? Or is it explicitly enough by just stating it is a Tutorial Party?

@Voldivh That's not a bad idea; @Yadunund , should we consider this?

Besides that, I think this looks pretty good, so I'm going to merge this so that the front page is not *too* out-of-date.  We can always do a follow-up PR here to beef up the front README.

2023-04-10 13:36 UTC, merged